### ISSUE TITLE
security warnings from firefox, chrome and safari

### ISSUE THREAD

**Issue by btorpey** [finos/openmama.github.io#2]
At least on my mac, every browser reports security issues with new website.

![Screen Shot 2020-10-01 at 10 47 23 AM](https://user-images.githubusercontent.com/6627450/94825413-2a25c300-03d4-11eb-935c-6978403a9efb.png)

**Comment by fquinner** [comment]
Think it has finally updated!

**Comment by WallStProg** [comment]
Yup - thanks.  Looking good!
